### ISSUE TITLE
log file is appended to if an experiments directory is reused

### ISSUE THREAD

**Issue by Ian-Mint** [Ian-Mint/pong-underwater-rl#18]
The log file is appended, but the history is over-written. Both should be over-written.

**Comment by Ian-Mint** [comment]
Actually, this is probably the behavior we want, especially if we are reusing the directory to continue training. This preserves the entire training log accurately. Thoughts @Yuanceli?

**Comment by Yuanceli** [comment]
I agree. We better keep the entire log so we can know details about the process
