### ISSUE TITLE
Hide the ball and left paddle positions

### ISSUE THREAD

**Issue by Ian-Mint** [Ian-Mint/pong-underwater-rl#2]
![image](https://user-images.githubusercontent.com/6959555/81865479-d39e1200-9522-11ea-898b-69c9f2c3a29e.png)

It's possible that the model could learn the meaning of the text at the bottom of the screen. It should be hidden from the agent.

**Comment by Yuanceli** [comment]
Yes I didnt notice that. I think it's better to have no text.

**Comment by Yuanceli** [comment]
I dont think the texts below are necessary. What about the upper scores? I think it should be removed too since in real world there aren't any 'scores' in the images for training. If we are only focusing on the game, I think it's fine to keep them

**Comment by Ian-Mint** [comment]
Yeah, I think the upper scores are fine. The model will already be getting
that information directly.
